import { installAgentClient } from './agent/agentClient';
import { createAgentConversation } from './agent/agentConversation';
import { installDramaCanvasBridge } from './agent/dramaCanvasBridge';
import { installDramaConversationShortcut } from './agent/dramaConversationShortcut';
import { installDramaConversationTools } from './agent/dramaConversationTools';
import { installStableCanvasClipboard } from './canvas/canvasClipboard';
import { installStableCanvasConnections } from './canvas/canvasConnections';
import { installStableCanvasContextActions } from './canvas/canvasContextActions';
import { installStableCanvasEditing } from './canvas/canvasEditing';
import { installStableCanvasGroups } from './canvas/canvasGroups';
import { installStableCanvasLayout } from './canvas/canvasLayout';
import { installStableCanvasNavigation } from './canvas/canvasNavigation';
import { installStableCanvasSelection } from './canvas/canvasSelection';
import { installWorkflowPresetComposition } from './canvas/workflowPresetComposition';
import { installBackendReconnectNotice } from './desktop/backendReconnectNotice';
import { installGenerationScheduler } from './generation/generationScheduler';
import { installGenerationRecovery } from './generation/generationRecovery';
import { installWorkflowRecoveryFetch } from './generation/workflowRecoveryBoundary';
import { installImageModeAdapter } from './generation/imageMode';
import { installMidjourneyReferenceAdapter } from './generation/midjourneyReferences';
import { installImageResultHistory } from './generation/imageResultHistory';
import { installAgentModelAvailability } from './generation/agentModelAvailability';
import { installModelPricing } from './generation/modelPicker';
import { createSourceSettingsClient } from './generation/sourceSettingsClient';
import { installVideoModeAdapter } from './generation/videoMode';
import { installStableDesignSystem } from './design/designSystem';
import { installProjectDashboardChrome } from './navigation/projectDashboardChrome';
import { installComfyLogPanel } from './local/comfyLogPanel';
import { installLocalRuntimeClient } from './local/localRuntimeClient';
import { createWorkflowManagerClient } from './local/workflowManagerClient';
import { installWorkflowManager } from './local/workflowManager';
import { installWorkflowCanvasNodes } from './local/workflowCanvasNodes';
import { installMediaEditing } from './media/mediaEditing';
import { installMediaDownloadFileName } from './media/mediaDownloadFileName';
import { installMediaNodeSizing } from './media/mediaNodeSizing';
import { installStableVideoPlayback } from './media/videoPlayback';
import { installMiniMaxH3CanvasAdapter } from './media/minimaxH3';
import { installMiniMaxPromptScroll } from './media/minimaxPromptScroll';
import { NativeStableMediaRenderer } from './media/nativeStableMediaRenderer';
import { startStableMediaEnhancement } from './media/stableMediaEnhancement';
import { installVideoWorkflows } from './media/videoWorkflows';
import { installNodeFramework } from './nodes/nodeFramework';
import { installCanvasAutoSave } from './persistence/canvasAutoSave';
import { installCanvasSession } from './persistence/canvasSession';
import { installPreferenceStore } from './persistence/preferenceStore';
import { installCanvasAppearance } from './appearance/canvasAppearance';
import { installPromptAssistant } from './prompt/promptAssistant';
import { installPromptExpand } from './prompt/promptExpand';
import { installPromptPresets } from './prompt/promptPresets';
import { installStoryboardClient } from './storyboard/storyboardClient';
import { installAgentSkillClient } from './skills/skillClient';
import { installSkillCommunity } from './skills/skillCommunity';

// 设置页和发行门禁都读取同一个构建戳；必须先于设计增强安装，避免首次打开设置时
// 仍然显示旧版或空版本。
document.documentElement.dataset.fisheraiBuild = __FISHERAI_BUILD__;

installWorkflowRecoveryFetch();
const dramaCanvasBridge = installDramaCanvasBridge();
installBackendReconnectNotice();
// Local workspace preferences load before any enhancement reads them (ADR-0035): one backend request.
await installPreferenceStore(window.fetch.bind(window));
installCanvasAppearance();
const sourceSettingsClient = createSourceSettingsClient();
installAgentModelAvailability(sourceSettingsClient);
installAgentClient();
const agentSkillClient = installAgentSkillClient();
installSkillCommunity(agentSkillClient);
installStableCanvasClipboard();
installStableCanvasConnections();
installStableCanvasContextActions();
installStableCanvasEditing();
installStableCanvasGroups();
installStableCanvasLayout();
installStableCanvasNavigation();
installStableCanvasSelection();
installWorkflowPresetComposition();
installMediaDownloadFileName();
installMediaNodeSizing();
installStableVideoPlayback();
installStableDesignSystem().observe();
installProjectDashboardChrome();
installCanvasSession();
installCanvasAutoSave();
installNodeFramework();
installImageModeAdapter();
installMidjourneyReferenceAdapter();
installVideoModeAdapter();
installImageResultHistory();
installGenerationScheduler();
installGenerationRecovery();
installModelPricing(sourceSettingsClient);
const localRuntimeClient = installLocalRuntimeClient();
const workflowManagerClient = createWorkflowManagerClient();
installWorkflowCanvasNodes(workflowManagerClient);
const agentConversation = createAgentConversation(() => dramaCanvasBridge.projectId());
installDramaConversationShortcut(dramaCanvasBridge, agentConversation);
installDramaConversationTools(dramaCanvasBridge, agentConversation);
installWorkflowManager(workflowManagerClient);
installComfyLogPanel(localRuntimeClient);
installMiniMaxH3CanvasAdapter();
installMiniMaxPromptScroll();
installVideoWorkflows();
installPromptAssistant();
installPromptExpand();
installPromptPresets();
installStoryboardClient();
installMediaEditing();
startStableMediaEnhancement({ renderer: new NativeStableMediaRenderer() });
